platform :ios,'8.0'
target 'CYInkeLive' do

pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'MJExtension'
pod 'Masonry'
pod 'MBProgressHUD'
# pod 'ReactiveCocoa'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/WeChat'
pod 'Reachability'
 
end
